export const ADD_TO_CART = 'ADD_TO_CART';
export const ADD_QUANTITY = 'ADD_QUANTITY';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const SUBTRACT_QUANTITY = 'SUBTRACT_QUANTITY';
export const EMPTY_CART = 'EMPTY_CART';
export const UPDATE_TAX_DETAILS = 'UPDATE_TAX_DETAILS';
